### ISSUE TITLE
Adding Linkedin Auth as participant verification option

### ISSUE THREAD

**Issue by m3data** [pol-is/openData#1]
I'm looking to use polis for engagement with public policy initiatives around regulated sharing of personal data. The mechanisms used to verify a unique participant like facebook and twitter create limits for diverse participation. i.e. not everyone has a facebook or twitter account. Adding Linkedin may increase the inclusion.

**Comment by m3data** [comment]
My bad. Realise this is not in the correct library so please move.

**Comment by metasoarous** [comment]
Please see https://github.com/compdemocracy/polis/issues/97 and 
https://github.com/compdemocracy/polis/issues/638.
