### ISSUE TITLE
License for data reuse

### ISSUE THREAD

**Issue by evamaxfield** [pol-is/openData#3]
Hey!

Thoughts on adding a license for reuse of this data? Would love to use a few of these datasets in a research study but it needs to be licensed for approval from my release compliance.

I know of a couple of licenses that generally work well for open source data:

* Creative Commons 4 BY Attribution
  * Plain language summary: https://creativecommons.org/licenses/by/4.0/
  * Plaintext: https://creativecommons.org/licenses/by/4.0/legalcode.txt

* Open Data Commons Attribution
  * Plain language summary: https://opendatacommons.org/licenses/by/summary/
  * Plaintext: https://opendatacommons.org/licenses/by/odc_by_1.0_public_text.txt

If either of these work for you, or if you want something else, let me know. I'm happy to make a PR to add whatever you want!

Let me know :)

**Comment by colinmegill** [comment]
Resolved in README
